#!/bin/bash

NAME=$1

# Define paths
DEFAULT_HTML_PATH="html-templates/default"
CUSTOM_HTML_PATH="html-templates/$NAME"

# Remove the target directory
rm -rf "src/lib/ui/html"

# Check if NAME is set and the custom directory exists
if [ -n "$NAME" ] && [ -d "$CUSTOM_HTML_PATH" ]; then
    echo "copy the custom template: $NAME"
    cp -r "$CUSTOM_HTML_PATH" "src/lib/ui/html"
else
    echo "copy the default template"
    cp -r "$DEFAULT_HTML_PATH" "src/lib/ui/html"
fi
