FROM nginx:1.20
#FROM nginx:1.20.1-alpine

RUN \
    apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./dist /usr/share/nginx/html/script
# COPY ./consent-request/dist /usr/share/nginx/html/ui

WORKDIR /usr/share/nginx/html
